### PR TITLE
rename con to jc and fix conflict with j

### LINKED ISSUE #93: Conflict of commands names
I am introducing a new command named `jc` for JuliaCon

It is also parsed by the `j` command. We should probably think a bit more about that issue.

I am temporarily using `con` instead of `jc`, but we will run into that trouble again in the future.

### PR DESCRIPTION
**Pull request by rmsrosa**
This fixes and closes #93

### CODE REVIEW

File: src/command/j.jl [hunk 1]
```diff
@@ -25,7 +25,7 @@ end
 function commander(c::Client, m::Message, ::Val{:julia_doc})
     # @info "julia_commander called"
     # @info "Message content" m.content m.author.username m.author.discriminator
-    startswith(m.content, COMMAND_PREFIX * "j") || return
+    startswith(m.content, COMMAND_PREFIX * "j ") || startswith(m.content, COMMAND_PREFIX * "j? ") || m.content == COMMAND_PREFIX * "j" || return
```
Comment (tk3369) [inline src/command/j.jl:28]: Can you break the long line? 

BlueStyle suggests 92 characters.
https://github.com/invenia/BlueStyle#synopsis

These formatting changes can be automated by the editor
https://github.com/invenia/BlueStyle#editor-configuration

**Review by tk3369 — COMMENTED** [review]
Great! I just have a minor suggestion.

File: src/command/j.jl (hunk 1 above)
Comment (rmsrosa) [reply src/command/j.jl]: Yeah, that is a good thing. I just did that. In this line and in a few others.

**Review by Azzaare — APPROVED** [review]
